name: Docker Build and Push

# Define o gatilho: roda sempre que houver um push na branch main
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout (baixa) o código do repositório na máquina do GitHub
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Faz o login no Docker Hub usando os Secrets que configuramos
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Configura o Buildx (ferramenta avançada do Docker para build)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Constrói a imagem e envia (push) para o Docker Hub
      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              seu-usuario-docker/meu-app-fastapi:latest
              seu-usuario-docker/meu-app-fastapi:${{ github.sha }}